# Generated by Django 5.1.5 on 2025-02-26 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0003_alter_customuser_addiction_detail_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(1)])),
                ('addiction_type', models.CharField(choices=[('drinking', 'Drinking'), ('smoking', 'Smoking'), ('drugs', 'Drugs')], max_length=10)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('patient_email', models.EmailField(max_length=254)),
                ('guider_email', models.EmailField(max_length=254)),
                ('guider_contact_number', models.CharField(max_length=15)),
                ('guider_relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('friend', 'Friend'), ('other', 'Other')], max_length=10)),
                ('other_relationship_specification', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='addiction_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('dob', models.DateField()),
                ('addiction_detail', models.TextField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('patient_phone_number', models.CharField(max_length=15)),
                ('date_of_join', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='addiction_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parent_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_set_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('position', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('patient_id', models.ManyToManyField(related_name='assigned_staff', to='apprehab.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='apprehab.staff'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='apprehab.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='apprehab.staff')),
            ],
        ),
    ]
