# Generated by Django 5.1.5 on 2025-02-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0004_addictiondetails_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='addictiondetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addictiondetails',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apprehab.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='patient_id',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='apprehab.patient'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Counselor', 'Counselor'), ('Psychiatrist', 'Psychiatrist'), ('Medical Officer', 'Medical Officer'), ('Support Staff', 'Support Staff'), ('Case Manager', 'Case Manager')], max_length=100),
        ),
    ]
