# Generated by Django 5.1.5 on 2025-03-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0005_remove_staff_designation_remove_staff_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_time', models.DateTimeField()),
                ('meeting_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_conferences', to='apprehab.patient')),
                ('staff', models.ManyToManyField(related_name='video_conferences', to='apprehab.staff')),
            ],
        ),
    ]
