# Generated by Django 5.1.5 on 2025-03-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0006_videoconference'),
    ]

    operations = [
        migrations.AddField(
            model_name='addictiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='addictiondetails',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
