# Generated by Django 5.1.5 on 2025-03-02 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0008_customuser_is_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoconference',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.RemoveField(
            model_name='videoconference',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='videoconference',
            name='staff',
        ),
        migrations.AddField(
            model_name='videoconference',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
