# Generated by Django 5.1.5 on 2025-03-02 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0009_alter_videoconference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='room_name',
            field=models.CharField(default='f403a5aa', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='video_conferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
