# Generated by Django 5.1.5 on 2025-03-02 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0010_videoconference_room_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoconference',
            options={},
        ),
        migrations.RemoveField(
            model_name='addictiondetails',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='addictiondetails',
            name='guider_email',
        ),
        migrations.RemoveField(
            model_name='addictiondetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addictiondetails',
            name='other_relationship_specification',
        ),
        migrations.RemoveField(
            model_name='addictiondetails',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='videoconference',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='videoconference',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='addictiondetails',
            name='guider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addictiondetails',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addiction_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addictiondetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='addiction_type',
            field=models.CharField(choices=[('alcohol', 'Alcohol'), ('drugs', 'Drugs'), ('gambling', 'Gambling'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='guider_contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='guider_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
