# Generated by Django 5.1.5 on 2025-03-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0011_alter_videoconference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addictiondetails',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='apprehab.staff'),
        ),
    ]
