# Generated by Django 5.1.5 on 2025-03-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0016_groupconference'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('counselor', 'Counselor'), ('therapist', 'Therapist')], max_length=100),
        ),
    ]
