# Generated by Django 5.1.5 on 2025-03-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0017_staff_created_at_staff_password_staff_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='join_request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('none', 'No Request')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='join_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addictiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupconference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupconference',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, choices=[('Counselor', 'Counselor'), ('Psychiatrist', 'Psychiatrist'), ('Medical Officer', 'Medical Officer'), ('Support Staff', 'Support Staff'), ('Case Manager', 'Case Manager')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='yogasession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='yogasession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
