# Generated by Django 5.1.5 on 2025-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0019_remove_videoconference_join_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='join_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='patient_join_request',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('none', 'No Request')], default='none', max_length=20),
        ),
    ]
