# Generated by Django 5.1.5 on 2025-03-05 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0020_videoconference_join_request_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addictiondetails',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='program_day',
            field=models.IntegerField(default=1, help_text='Day of the 7-day program (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='yoga',
            name='program_day',
            field=models.IntegerField(default=1, help_text='Day of the 7-day program (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='yogasession',
            name='program_day',
            field=models.IntegerField(default=1, help_text='Day of the 7-day program (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
