# Generated by Django 5.1.5 on 2025-03-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0023_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='user',
            new_name='patient',
        ),
    ]
