# Generated by Django 5.0.2 on 2025-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0024_rename_user_testimonial_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='addictiondetails',
            name='guider_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
